### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ikpa** [larikkai/ot-harjoitustyo#2]
Projekti ladattu 24.4, klo 13:25.

## Yleistä
Koodi on helposti luettavaa; muuttujien ja luokkien nimet ovat kaikkialla koodissa selkeitä, luokat on jaoteltu selkeisiin paketteihin, ja koodin tarinaa on helppo seurata. Muutamia virheitä kuitenkin löytyy.  
## Domain 
Tämä paketti sisältää käyttäjää ja tehtävää kuvaavat luokat User ja Task, sekä pääasiallisen ohjelmalogiikan sisältävän AlgoritmitehtavageneraattoriService-luokan. Tämän paketin koodi on erittäin selkeää. Ainoat virheet mitkä keksin on Task-luokan kategoriaa kuvaavan muuttujan "gategory" kirjoitusasu (oikea kirjoitusasu "category"), sekä AlgoritmitehtavageneraattoriService-luokan turhan pitkä nimi.
## Dao
Tämä pakkaus sisältää datatiedostojen lukemiseen tarvittavat TaskDao ja UserDao -interfacet, sekä luokat FileTaskDao ja FileUserDao. Luokkien nimentä on selkeää, ja metodeilla on selvät, yksittäiset tehtävät, eivätkä ole liian pitkiä.  

Tiedoston lukemista ja kirjoittamista tapahtuu molemmissa luokissa, siinä missä koodin laatuvaatimuksissa sitä saisi tapahtua vain yhdessä luokassa. Lisäksi luokka FileTaskDao:n yksi muuttujista on luokka FileUserDao; ehkä luokat voisi mahdollisesti yhdistää?   

FileTaskDao:n rivillä 33 haetaankäyttäjää tietyllä nimellä stream()-komennon avulla. Tämä sama toiminto on kuitenkin toteutettu jo FileUserDao-luokan findByUsername()-metodissa. Korvaamalla stream tällä metodilla tekisi koodista helpommin luettavaa.   

Molemmat luokan interfacet ovat koodin tämänhetkisessä tilassa turhia, sillä kumpaakin implementoi vain yksi luokka. Kyseisiä luokkia voisi kutsua suoraan AlgoritmitehtavageneraattoriService-luokassa.  

Kummassakin luokassa voisi olla oma File-olio String-muuttujan sijasta datatiedoston säilyttämiseksi. Näin luku- ja kirjoitusmetodeissa ei tarvitsisi luoda uutta File-oliota scanneria tai writeria luodessa.
## Testit
Testejä on jokaiselle luokalle, lukuunottamatta interface-olioita ja ui-pakettia. Testejä on yhteensä 35, ja kaikki menevät läpi. Testikattavuus on 45%, mikä on tässä vaiheessa kurssia tarpeeksi. Testitiedostot eivät sisällä Netbeansin itse-generoimia testejä, kuten laatuvaatimuksissa sanotaan. Testit eivät muutenkaan sisällä suurempia laatuvirheitä.
## Muut virheet
Koodia ei pysty ajamaan, latasi sen sitten "Clone or Download" napin avulla, tai releaseistä jar-muodossa kaikkien oheistiedostojen kanssa. Ohjelma vaatii tiedostot "users.txt" sekä "tasks.txt" toimiakseen. Lisäämällä nämä tiedostot manuaalisesti projektikansioon sallii ohjelman ajamisen, mutta tyhjien tiedostojen lukeminen aiheuttaa kaksi ArrayIndexOutOfBoundsException-virhettä, eikä ohjelmaa voi tämän vuoksi käyttää kirjautumisruutua pitemmälle. Ongelman voisi korjata lisäämällä kyseiset tiedostot projektiin, sekä luomalla kumpaankin Dao-luokkaan metodin, joka tarkistaa, onko tiedosto tyhjä ennen kuin se luetaan.

**Comment by larikkai** [comment]
Kiitos katselmoinnista, korjauksia tehty.
   - [x] Task-luokan kategoriaa kuvaavan muuttujan "gategory" kirjoitusasu (oikea kirjoitusasu "category")
   - [x] stream vaihdettu metodiin
   - [ ] koodin vastaamaan laatuvaatimuksia (file)

## Muut virheet
Pystyn itse ajamaan koodin (release+clone/download) sekä windowsissa, että cubblilla. Tiedostoja pyydetään ja ikävä virhe näkyy, tiedostot kuitenkin luodaan jos niitä ei ole kun luodaan uusi käyttäjä tai tehtävä. Jos aikaa vielä löytyy niin olisi mielenkiintoista kuulla estääkö nämä virheet käytön / pysähtyykö sovellus?

ArrayIndexOutOfBoundsException johtuu että tiedostossasi oli tyhjiä rivejä. Täytyy tämä valitoida pois.

**Comment by ikpa** [comment]
Yritin uudestaan ajaa ohjelman. Näyttää tosiaan siltä, että virheviesteistä huolimatta ohjelmaa voi käyttää normaalisti. Katselmointia tehdessäni oletin, että tiedostojen puute estäisi ohjelman käytön kokonaan, enkä siksi huomannut että ohjelma luo uudet tiedostot. Pahoitteluni siis tästä. Itse virheviestien poistaminen olisi kuitenkin hyvä; koodin laatuvaatimuksissa halutaan, että koodi ei tulosta ollenkaan stacktracea.
